Highlight pattern in founded strings #17
mkpankov/greprs pull request #19
Opened 2017-08-29 19:48 UTC by iloskutov

2017-08-31 09:44 UTC, mkpankov commented
Спасибо за PR, позже на этой неделе посмотрю

2017-09-06 09:13 UTC, mkpankov requested changes

2017-09-06 09:13 UTC, mkpankov commented on src/lib.rs
> +fn println_highlight(line: &String, span_chars: (usize, usize)) {
`line: &String` - антипаттерн. т.к. принимаешь ссылку и всё равно клонируешь ниже, лучше принимать `&str` - тогда можно передать любую строку, а не только на куче.

`span_chars` на стороне вызывающего называется `span_bytes`.

2017-09-06 09:13 UTC, mkpankov commented on src/lib.rs
> +    let mut l0 = line.clone();
Может всё-таки не клонировать ради подсветки-то?

Сделать срез (не проверял этот код):
```rust
let (match_start, match_end) = span_bytes;
let line_before_match = &line[..match_start];
let line_after_match = &line[match_end+1..];
...
write!(term, "{}, line_before_match).unwrap();
...
```

2017-09-06 09:13 UTC, mkpankov commented on src/lib.rs
> +        println_highlight(lines.get(i.line - 1).unwrap(), i.line_match.span_bytes);
`i.line - 1` начинает напрягать. Давай может исправим #6 заодно? В matches должна быть нумерация с нуля, которая преобразуется в человеческую только при печати.

2017-09-07 20:25 UTC, iloskutov commented
Вроде все поправил

2017-10-24 14:08 UTC, mkpankov approved these changes

2017-10-24 14:09 UTC, mkpankov commented
Не прошло и года, я посмотрел на исправления

2017-10-24 14:09 UTC, merged