Add recursive search #4
mkpankov/greprs pull request #8
Opened 2017-06-28 20:12 UTC by iloskutov

2017-07-03 09:23 UTC, mkpankov requested changes
Надо бы добавить тест.

Навскидку, его добавление проявит необходимость переделки walk_dirs - она ничего не возвращает, нормально не протестируешь. Я бы сказал, она должна возвращать итератор. Не уверен, что так сходу получится, но попробовать надо.

2017-07-05 13:23 UTC, iloskutov commented
Ок, попробую так.

2017-07-28 09:52 UTC, mkpankov commented on src/lib.rs
> +    let mut opts = 0;
Стрёмная, конечно, приблуда. Может надо будет на нормальный парсер аргументов перейти.

2017-07-28 10:01 UTC, mkpankov requested changes
Надо с ошибками в WalkDir разобраться, и ещё по мелочи

2017-07-28 10:01 UTC, mkpankov commented on src/lib.rs
> +                writeln!(io::stderr(), "Error: {}.", e.description()).unwrap();
Стрёмно. Это не забота итератора писать ошибки (и тем более выходить из программы).

Пусть он возвращает Result, и `WalkDir::new` тоже возвращает Result.

2017-07-28 10:01 UTC, mkpankov commented on src/lib.rs
> +        match maybe_entry {
То же самое. `Item` должен быть `io::Result<String>`

2017-07-28 10:01 UTC, mkpankov commented on src/main.rs
> +            usage();
Тогда здесь тоже `writeln!(io::stderr(), "Not enough arguments").unwrap();`

2017-07-28 10:01 UTC, mkpankov commented on src/lib.rs
> +    let files: Vec<_> = WalkDir::new(&test_data_path).collect();
Чтобы не принимать строчки, а принимать всё, что похоже на пути, можно в `WalkDir::new` сделать так:
```rust
fn new<P: AsRef<Path>>(path: P) -> WalkDir {
```

(подглядел как в стандартной библиотеке определён open)

2017-07-29 11:50 UTC, iloskutov commented on src/lib.rs
> +    let mut opts = 0;
Согласен. Можно таску завести на это

2017-07-29 11:50 UTC, iloskutov commented on src/lib.rs
> +                writeln!(io::stderr(), "Error: {}.", e.description()).unwrap();
ок, копипаста с предыдущей реализации )

2017-08-01 10:12 UTC, mkpankov commented on src/lib.rs
> +        let dir = fs::read_dir(path)?;
:+1:

2017-08-01 10:20 UTC, mkpankov requested changes

2017-08-01 10:20 UTC, mkpankov commented on src/lib.rs
> +    let test_data_path = std::env::current_dir().unwrap();
Хрупко. В моём тесте такое можно, потому что мне нужна любая директория, а тебе нужна та, откуда найдётся haystack. Лучше взять parent от current_exe и т.д.

2017-08-01 10:30 UTC, iloskutov commented on src/lib.rs
> +    let test_data_path = std::env::current_dir().unwrap();
Мне кажется наоборот, куда cargo скомпилит бинарик вещь не очень надёжная, а тест запускается через cargo test с корня проекта, и там все файлы лежат, как положили их в репозиторий. В любом случае, при тесте с внешними данными их или нужно создавать в самом тесте или надеялся на инструменты и наличие нужных данных.

2017-08-01 11:20 UTC, mkpankov commented on src/lib.rs
> +    let test_data_path = std::env::current_dir().unwrap();
Просто по факту расположение бинарников не менялось, кажется, никогда. А запустить cargo test из поддиректории корня можно.

2017-08-01 20:43 UTC, mkpankov approved these changes

2017-08-02 09:59 UTC, merged